<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\ProductionProgress\PartialView\" />
    <Folder Include="Views\ProductionDepartment\PartialView\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sub_Entities\Sub_Entities.csproj" />
    <ProjectReference Include="..\Sub_Services\Sub_Services.csproj" />
  </ItemGroup>

</Project>
