// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ActivityLog
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid? PageId { get; set; }

    public string Action { get; set; }

    public string ObjectType { get; set; }

    public string ObjectId { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string Description { get; set; }

    public string Ipaddress { get; set; }

    public string UserAgent { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual Page Page { get; set; }

    public virtual User User { get; set; }
}