// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class DailyOutput
{
    public Guid Id { get; set; }

    public Guid ProductionInfoId { get; set; }

    public Guid ProductionMachineId { get; set; }

    public Guid? StyleInfoId { get; set; }

    public int? TotalOutputNumber { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<DailyOutputDetail> DailyOutputDetails { get; set; } = new List<DailyOutputDetail>();

    public virtual ProductionInfo ProductionInfo { get; set; }

    public virtual ProductionMachine ProductionMachine { get; set; }

    public virtual StyleInfo StyleInfo { get; set; }
}