// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class DailyOutputDetail
{
    public Guid Id { get; set; }

    public Guid? DailyOutputId { get; set; }

    public Guid StyleDetailId { get; set; }

    public int? OutputNumber { get; set; }

    public TimeOnly InputTime { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual DailyOutput DailyOutput { get; set; }

    public virtual StyleDetail StyleDetail { get; set; }
}