// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ExcelMonitorLog
{
    public long Id { get; set; }

    public Guid ExcelFileId { get; set; }

    public string EventType { get; set; }

    public string Message { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ExcelFile ExcelFile { get; set; }
}