// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ExcelSheetConfig
{
    public Guid Id { get; set; }

    public Guid ExcelFileId { get; set; }

    public string SheetName { get; set; }

    public string GroupColumn { get; set; }

    public string RowKeyColumns { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ExcelFile ExcelFile { get; set; }
}