// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ExcelSheetConfig
{
    public Guid Id { get; set; }

    public Guid ExcelFileId { get; set; }

    public string SheetName { get; set; }

    public string GroupColumn { get; set; }

    public string RowKeyColumns { get; set; }

    /// <summary>
    /// Số dòng bỏ qua trước khi đọc header.
    /// 0 = Row 1 là header (mặc định).
    /// 1 = bỏ qua Row 1 (title), dùng Row 2 làm header.
    /// </summary>
    public int HeaderRowIndex { get; set; } = 0;

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ExcelFile ExcelFile { get; set; }
}