// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ExcelChangeLog
{
    public long Id { get; set; }

    public Guid ExcelFileId { get; set; }

    public string SheetName { get; set; }

    public int? ExcelRowNumber { get; set; }

    public string RowKey { get; set; }

    public string GroupName { get; set; }

    public string ChangeType { get; set; }

    public string ColumnName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string OldFormula { get; set; }

    public string NewFormula { get; set; }

    public string OldGroupName { get; set; }

    public string NewGroupName { get; set; }

    public DateTime ChangeDate { get; set; }

    public string UserName { get; set; }

    public string ComputerName { get; set; }

    public virtual ExcelFile ExcelFile { get; set; }
}