// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ExcelFile
{
    public Guid Id { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string FileType { get; set; }

    public int Status { get; set; }

    public string LastHash { get; set; }

    public DateTime? LastReadDate { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<ExcelChangeLog> ExcelChangeLogs { get; set; } = new List<ExcelChangeLog>();

    public virtual ICollection<ExcelMonitorLog> ExcelMonitorLogs { get; set; } = new List<ExcelMonitorLog>();

    public virtual ICollection<ExcelSheetConfig> ExcelSheetConfigs { get; set; } = new List<ExcelSheetConfig>();

    public virtual ICollection<ExcelSnapshotRow> ExcelSnapshotRows { get; set; } = new List<ExcelSnapshotRow>();
}