// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ExcelSnapshotRow
{
    public long Id { get; set; }

    public Guid ExcelFileId { get; set; }

    public string SheetName { get; set; }

    public int? ExcelRowNumber { get; set; }

    public string RowKey { get; set; }

    public string GroupName { get; set; }

    public string RowHash { get; set; }

    public string DataJson { get; set; }

    public string FormulaJson { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ExcelFile ExcelFile { get; set; }
}