// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class Page
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string ControllerName { get; set; }

    public string Path { get; set; }

    public Guid? ParentId { get; set; }

    public int SortOrder { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<Page> InverseParent { get; set; } = new List<Page>();

    public virtual Page Parent { get; set; }

    public virtual ICollection<RolePagePermission> RolePagePermissions { get; set; } = new List<RolePagePermission>();

    public virtual ICollection<UserPagePermission> UserPagePermissions { get; set; } = new List<UserPagePermission>();
}