// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ProductionDepartment
{
    public Guid Id { get; set; }

    public string DepartmentName { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<ProductionDepartmentLayout> ProductionDepartmentLayouts { get; set; } = new List<ProductionDepartmentLayout>();

    public virtual ICollection<ProductionInfo> ProductionInfos { get; set; } = new List<ProductionInfo>();

    public virtual ICollection<ProductionMachine> ProductionMachines { get; set; } = new List<ProductionMachine>();
}