// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ProductionDepartmentLayout
{
    public Guid Id { get; set; }

    public Guid ProductionDepartmentId { get; set; }

    public string Name { get; set; }

    public int RowCount { get; set; }

    public int ColumnCount { get; set; }

    public decimal? CellWidth { get; set; }

    public decimal? CellHeight { get; set; }

    public decimal? Gap { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<ProductLayoutItem> ProductLayoutItems { get; set; } = new List<ProductLayoutItem>();

    public virtual ProductionDepartment ProductionDepartment { get; set; }
}