// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ProductLayoutItem
{
    public Guid Id { get; set; }

    public Guid ProductionMachineId { get; set; }

    public Guid ProductionDepartmentLayoutId { get; set; }

    public decimal? X { get; set; }

    public decimal? Y { get; set; }

    public decimal? Width { get; set; }

    public decimal? Height { get; set; }

    public int? RowIndex { get; set; }

    public int? ColumnIndex { get; set; }

    public int? SortOrder { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ProductionDepartmentLayout ProductionDepartmentLayout { get; set; }

    public virtual ProductionMachine ProductionMachine { get; set; }
}