// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class ProductionInfo
{
    public Guid Id { get; set; }

    public Guid ProductionDepartmentId { get; set; }

    public string Line { get; set; }

    public string Style { get; set; }

    public string Spmain { get; set; }

    public int? TotalQty { get; set; }

    public int? FinishQty { get; set; }

    public string Color { get; set; }

    public int? Target { get; set; }

    public DateOnly? InlineLine { get; set; }

    public DateOnly? InlineDepartment { get; set; }

    public string Remark { get; set; }

    public int? Machine { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<DailyOutput> DailyOutputs { get; set; } = new List<DailyOutput>();

    public virtual ProductionDepartment ProductionDepartment { get; set; }
}