// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class RolePagePermission
{
    public Guid Id { get; set; }

    public Guid RoleId { get; set; }

    public Guid PageId { get; set; }

    public Guid PermissionId { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual Page Page { get; set; }

    public virtual Permission Permission { get; set; }

    public virtual Role Role { get; set; }
}