// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sub_Entities.Entities;

public partial class SNP_SubSystemDBContext : DbContext
{
    public SNP_SubSystemDBContext(DbContextOptions<SNP_SubSystemDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<DailyOutput> DailyOutputs { get; set; }

    public virtual DbSet<DailyOutputDetail> DailyOutputDetails { get; set; }

    public virtual DbSet<ExcelChangeLog> ExcelChangeLogs { get; set; }

    public virtual DbSet<ExcelFile> ExcelFiles { get; set; }

    public virtual DbSet<ExcelMonitorLog> ExcelMonitorLogs { get; set; }

    public virtual DbSet<ExcelSheetConfig> ExcelSheetConfigs { get; set; }

    public virtual DbSet<ExcelSnapshotRow> ExcelSnapshotRows { get; set; }

    public virtual DbSet<Page> Pages { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<ProductLayoutItem> ProductLayoutItems { get; set; }

    public virtual DbSet<ProductionDepartment> ProductionDepartments { get; set; }

    public virtual DbSet<ProductionDepartmentLayout> ProductionDepartmentLayouts { get; set; }

    public virtual DbSet<ProductionInfo> ProductionInfos { get; set; }

    public virtual DbSet<ProductionMachine> ProductionMachines { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePagePermission> RolePagePermissions { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<StyleDetail> StyleDetails { get; set; }

    public virtual DbSet<StyleInfo> StyleInfos { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserPagePermission> UserPagePermissions { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Activity__3214EC27C61975DC");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.ObjectId)
                .HasMaxLength(100)
                .HasColumnName("ObjectID");
            entity.Property(e => e.ObjectType).HasMaxLength(100);
            entity.Property(e => e.PageId).HasColumnName("PageID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserAgent).HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Page).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.PageId)
                .HasConstraintName("FK_Log_Page");

            entity.HasOne(d => d.User).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Log_User");
        });

        modelBuilder.Entity<DailyOutput>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DailyOut__3214EC27E46CC6F3");

            entity.ToTable("DailyOutput");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.ProductionInfoId).HasColumnName("ProductionInfoID");
            entity.Property(e => e.ProductionMachineId).HasColumnName("ProductionMachineID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleInfoId).HasColumnName("StyleInfoID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ProductionInfo).WithMany(p => p.DailyOutputs)
                .HasForeignKey(d => d.ProductionInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DailyOutput_ProductionInfo");

            entity.HasOne(d => d.ProductionMachine).WithMany(p => p.DailyOutputs)
                .HasForeignKey(d => d.ProductionMachineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DailyOutput_ProductionMachine1");

            entity.HasOne(d => d.StyleInfo).WithMany(p => p.DailyOutputs)
                .HasForeignKey(d => d.StyleInfoId)
                .HasConstraintName("FK_DailyOutput_StyleInfo");
        });

        modelBuilder.Entity<DailyOutputDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DailyOut__3214EC27D8FFD329");

            entity.ToTable("DailyOutputDetail");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DailyOutputId).HasColumnName("DailyOutputID");
            entity.Property(e => e.InputTime).HasDefaultValueSql("(CONVERT([time],getdate()))");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleDetailId).HasColumnName("StyleDetailID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.DailyOutput).WithMany(p => p.DailyOutputDetails)
                .HasForeignKey(d => d.DailyOutputId)
                .HasConstraintName("FK_DailyOutputDetail_DailyOutput");

            entity.HasOne(d => d.StyleDetail).WithMany(p => p.DailyOutputDetails)
                .HasForeignKey(d => d.StyleDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DailyOutputDetail_StyleDetail");
        });

        modelBuilder.Entity<ExcelChangeLog>(entity =>
        {
            entity.ToTable("ExcelChangeLog");

            entity.HasIndex(e => e.ChangeType, "IX_ExcelChangeLog_ChangeType");

            entity.HasIndex(e => e.ExcelFileId, "IX_ExcelChangeLog_File");

            entity.HasIndex(e => new { e.ExcelFileId, e.ChangeDate }, "IX_ExcelChangeLog_File_Date").IsDescending(false, true);

            entity.HasIndex(e => new { e.ExcelFileId, e.GroupName }, "IX_ExcelChangeLog_Group");

            entity.HasIndex(e => new { e.ExcelFileId, e.RowKey }, "IX_ExcelChangeLog_RowKey");

            entity.HasIndex(e => new { e.ExcelFileId, e.SheetName }, "IX_ExcelChangeLog_Sheet");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ChangeDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelChangeLog_ChangeDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ChangeType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ColumnName).HasMaxLength(255);
            entity.Property(e => e.ComputerName).HasMaxLength(255);
            entity.Property(e => e.ExcelFileId).HasColumnName("ExcelFileID");
            entity.Property(e => e.GroupName).HasMaxLength(255);
            entity.Property(e => e.NewGroupName).HasMaxLength(255);
            entity.Property(e => e.OldGroupName).HasMaxLength(255);
            entity.Property(e => e.OldRowKey).HasMaxLength(1000).IsRequired(false);
            entity.Property(e => e.NewRowKey).HasMaxLength(1000).IsRequired(false);
            entity.Property(e => e.RowKey).HasMaxLength(1000);
            entity.Property(e => e.SheetName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UserName).HasMaxLength(255);

            entity.HasOne(d => d.ExcelFile).WithMany(p => p.ExcelChangeLogs)
                .HasForeignKey(d => d.ExcelFileId)
                .HasConstraintName("FK_ExcelChangeLog_ExcelFile");
        });

        modelBuilder.Entity<ExcelFile>(entity =>
        {
            entity.ToTable("ExcelFile");

            entity.HasIndex(e => e.FilePath, "IX_ExcelFile_FilePath");

            entity.HasIndex(e => e.Status, "IX_ExcelFile_Status");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelFile_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.FileType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LastHash)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.LastReadDate).HasColumnType("datetime");
            entity.Property(e => e.Status).HasDefaultValue(1, "DF_ExcelFile_Status");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelFile_UpdateDate")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<ExcelMonitorLog>(entity =>
        {
            entity.ToTable("ExcelMonitorLog");

            entity.HasIndex(e => new { e.ExcelFileId, e.CreateDate }, "IX_ExcelMonitorLog_File_Date").IsDescending(false, true);

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelMonitorLog_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ExcelFileId).HasColumnName("ExcelFileID");

            entity.HasOne(d => d.ExcelFile).WithMany(p => p.ExcelMonitorLogs)
                .HasForeignKey(d => d.ExcelFileId)
                .HasConstraintName("FK_ExcelMonitorLog_ExcelFile");
        });

        modelBuilder.Entity<ExcelSheetConfig>(entity =>
        {
            entity.ToTable("ExcelSheetConfig");

            entity.HasIndex(e => e.ExcelFileId, "IX_ExcelSheetConfig_ExcelFileID");

            entity.HasIndex(e => new { e.ExcelFileId, e.SheetName }, "UX_ExcelSheetConfig_File_Sheet").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelSheetConfig_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ExcelFileId).HasColumnName("ExcelFileID");
            entity.Property(e => e.GroupColumn).HasMaxLength(255);
            entity.Property(e => e.RowKeyColumns).HasMaxLength(1000);
            entity.Property(e => e.SheetName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1, "DF_ExcelSheetConfig_Status");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelSheetConfig_UpdateDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ExcelFile).WithMany(p => p.ExcelSheetConfigs)
                .HasForeignKey(d => d.ExcelFileId)
                .HasConstraintName("FK_ExcelSheetConfig_ExcelFile");
        });

        modelBuilder.Entity<ExcelSnapshotRow>(entity =>
        {
            entity.ToTable("ExcelSnapshotRow");

            entity.HasIndex(e => new { e.ExcelFileId, e.SheetName }, "IX_ExcelSnapshotRow_File_Sheet");

            entity.HasIndex(e => new { e.ExcelFileId, e.SheetName, e.GroupName }, "IX_ExcelSnapshotRow_Group");

            entity.HasIndex(e => new { e.ExcelFileId, e.SheetName, e.RowKey }, "IX_ExcelSnapshotRow_RowKey");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF_ExcelSnapshotRow_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ExcelFileId).HasColumnName("ExcelFileID");
            entity.Property(e => e.GroupName).HasMaxLength(255);
            entity.Property(e => e.RowHash)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.RowKey)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.SheetName)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.ExcelFile).WithMany(p => p.ExcelSnapshotRows)
                .HasForeignKey(d => d.ExcelFileId)
                .HasConstraintName("FK_ExcelSnapshotRow_ExcelFile");
        });

        modelBuilder.Entity<Page>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pages__3214EC2770E4FE40");

            entity.HasIndex(e => e.Code, "UQ__Pages__A25C5AA75D37E892").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ControllerName).HasMaxLength(100);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.Path).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Pages_Parent");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Permissi__3214EC2774AD5E32");

            entity.HasIndex(e => e.Code, "UQ__Permissi__A25C5AA7C2D0DFB0").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductLayoutItem>(entity =>
        {
            entity.ToTable("ProductLayoutItem");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Height).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.ProductionDepartmentLayoutId).HasColumnName("ProductionDepartmentLayoutID");
            entity.Property(e => e.ProductionMachineId).HasColumnName("ProductionMachineID");
            entity.Property(e => e.Status).HasDefaultValue(1, "DF__ProductLa__Statu__3B40CD36");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.Width).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.X).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Y).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ProductionDepartmentLayout).WithMany(p => p.ProductLayoutItems)
                .HasForeignKey(d => d.ProductionDepartmentLayoutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductLayoutItem_ProductionDepartmentLayout");

            entity.HasOne(d => d.ProductionMachine).WithMany(p => p.ProductLayoutItems)
                .HasForeignKey(d => d.ProductionMachineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductLayoutItem_ProductionMachine");
        });

        modelBuilder.Entity<ProductionDepartment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC2780CEDF05");

            entity.ToTable("ProductionDepartment");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DepartmentName).HasMaxLength(255);
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductionDepartmentLayout>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC277115E6FE");

            entity.ToTable("ProductionDepartmentLayout");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CellHeight).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CellWidth).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Gap).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.ProductionDepartment).WithMany(p => p.ProductionDepartmentLayouts)
                .HasForeignKey(d => d.ProductionDepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionDepartmentLayout_ProductionDepartment");
        });

        modelBuilder.Entity<ProductionInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC27153C1330");

            entity.ToTable("ProductionInfo");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.Color)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FinishQty).HasColumnName("FinishQTY");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Line)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.Remark).HasMaxLength(255);
            entity.Property(e => e.Spmain)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SPMain");
            entity.Property(e => e.Style)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ProductionDepartment).WithMany(p => p.ProductionInfos)
                .HasForeignKey(d => d.ProductionDepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionInfo_ProductionDepartment");
        });

        modelBuilder.Entity<ProductionMachine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC278D2C1BF7");

            entity.ToTable("ProductionMachine");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())", "DF__ProductionMa__ID__5AEE82B9")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF__Productio__Creat__5CD6CB2B")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.MachineNumber)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.Status).HasDefaultValue(1, "DF__Productio__Statu__5BE2A6F2");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())", "DF__Productio__Updat__5DCAEF64")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ProductionDepartment).WithMany(p => p.ProductionMachines)
                .HasForeignKey(d => d.ProductionDepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionMachine_ProductionDepartment");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC273C936162");

            entity.HasIndex(e => e.Code, "UQ__Roles__A25C5AA7DC73E51A").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<RolePagePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RolePage__3214EC27FACE9599");

            entity.HasIndex(e => new { e.RoleId, e.PageId, e.PermissionId }, "UQ_RolePagePermissions").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PageId).HasColumnName("PageID");
            entity.Property(e => e.PermissionId).HasColumnName("PermissionID");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Page).WithMany(p => p.RolePagePermissions)
                .HasForeignKey(d => d.PageId)
                .HasConstraintName("FK_RPP_Page");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePagePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("FK_RPP_Permission");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePagePermissions)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_RPP_Role");
        });

        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_SystemSetting");

            entity.ToTable("Setting");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<StyleDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StyleDet__3214EC27BE917A27");

            entity.ToTable("StyleDetail");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DetailName).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleInfoId).HasColumnName("StyleInfoID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.StyleInfo).WithMany(p => p.StyleDetails)
                .HasForeignKey(d => d.StyleInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StyleDetail_StyleInfo");
        });

        modelBuilder.Entity<StyleInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StyleInf__3214EC2780B26A2A");

            entity.ToTable("StyleInfo");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleCode).HasMaxLength(100);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC2749C0636F");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E4505ABDEB").IsUnique();

            entity.HasIndex(e => e.Msnv, "UQ__Users__6CB3885EDC394B36").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105347083461A").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())", "DF__Users__ID__5224328E")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF__Users__CreateDat__540C7B00")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.HashCode)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Msnv)
                .HasMaxLength(50)
                .HasColumnName("MSNV");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1, "DF__Users__Status__531856C7");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())", "DF__Users__UpdateDat__55009F39")
                .HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UserPagePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserPage__3214EC276D06A3D0");

            entity.HasIndex(e => new { e.UserId, e.PageId, e.PermissionId }, "UQ_UserPagePermissions").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsGranted).HasDefaultValue(1);
            entity.Property(e => e.PageId).HasColumnName("PageID");
            entity.Property(e => e.PermissionId).HasColumnName("PermissionID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Page).WithMany(p => p.UserPagePermissions)
                .HasForeignKey(d => d.PageId)
                .HasConstraintName("FK_UPP_Page");

            entity.HasOne(d => d.Permission).WithMany(p => p.UserPagePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("FK_UPP_Permission");

            entity.HasOne(d => d.User).WithMany(p => p.UserPagePermissions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UPP_User");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3214EC27FC01C4B6");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "UQ_UserRoles").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_UserRoles_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRoles_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}