// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sub_Entities.Entities;

public partial class SNP_SubSystemDBContext : DbContext
{
    public SNP_SubSystemDBContext(DbContextOptions<SNP_SubSystemDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DailyOutput> DailyOutputs { get; set; }

    public virtual DbSet<DailyOutputDetail> DailyOutputDetails { get; set; }

    public virtual DbSet<ProductLayoutItem> ProductLayoutItems { get; set; }

    public virtual DbSet<ProductionDepartment> ProductionDepartments { get; set; }

    public virtual DbSet<ProductionDepartmentLayout> ProductionDepartmentLayouts { get; set; }

    public virtual DbSet<ProductionInfo> ProductionInfos { get; set; }

    public virtual DbSet<ProductionMachine> ProductionMachines { get; set; }

    public virtual DbSet<StyleDetail> StyleDetails { get; set; }

    public virtual DbSet<StyleInfo> StyleInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DailyOutput>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DailyOut__3214EC27FCBDA101");

            entity.ToTable("DailyOutput");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.ProductionInfoId).HasColumnName("ProductionInfoID");
            entity.Property(e => e.ProductionMachineId).HasColumnName("ProductionMachineID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleInfoId).HasColumnName("StyleInfoID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ProductionInfo).WithMany(p => p.DailyOutputs)
                .HasForeignKey(d => d.ProductionInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DailyOutput_ProductionInfo");

            entity.HasOne(d => d.ProductionMachine).WithMany(p => p.DailyOutputs)
                .HasForeignKey(d => d.ProductionMachineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DailyOutput_ProductionMachine1");

            entity.HasOne(d => d.StyleInfo).WithMany(p => p.DailyOutputs)
                .HasForeignKey(d => d.StyleInfoId)
                .HasConstraintName("FK_DailyOutput_StyleInfo");
        });

        modelBuilder.Entity<DailyOutputDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DailyOut__3214EC2761FC7F70");

            entity.ToTable("DailyOutputDetail");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DailyOutputId).HasColumnName("DailyOutputID");
            entity.Property(e => e.InputTime).HasDefaultValueSql("(CONVERT([time],getdate()))");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleDetailId).HasColumnName("StyleDetailID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.DailyOutput).WithMany(p => p.DailyOutputDetails)
                .HasForeignKey(d => d.DailyOutputId)
                .HasConstraintName("FK_DailyOutputDetail_DailyOutput");

            entity.HasOne(d => d.StyleDetail).WithMany(p => p.DailyOutputDetails)
                .HasForeignKey(d => d.StyleDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DailyOutputDetail_StyleDetail");
        });

        modelBuilder.Entity<ProductLayoutItem>(entity =>
        {
            entity.ToTable("ProductLayoutItem");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Height).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.ProductionDepartmentLayoutId).HasColumnName("ProductionDepartmentLayoutID");
            entity.Property(e => e.ProductionMachineId).HasColumnName("ProductionMachineID");
            entity.Property(e => e.Status).HasDefaultValue(1, "DF__ProductLa__Statu__3B40CD36");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.Width).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.X).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Y).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ProductionDepartmentLayout).WithMany(p => p.ProductLayoutItems)
                .HasForeignKey(d => d.ProductionDepartmentLayoutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductLayoutItem_ProductionDepartmentLayout");

            entity.HasOne(d => d.ProductionMachine).WithMany(p => p.ProductLayoutItems)
                .HasForeignKey(d => d.ProductionMachineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductLayoutItem_ProductionMachine");
        });

        modelBuilder.Entity<ProductionDepartment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC27B4AA4024");

            entity.ToTable("ProductionDepartment");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DepartmentName).HasMaxLength(255);
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<ProductionDepartmentLayout>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC272D441572");

            entity.ToTable("ProductionDepartmentLayout");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CellHeight).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CellWidth).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Gap).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.ProductionDepartment).WithMany(p => p.ProductionDepartmentLayouts)
                .HasForeignKey(d => d.ProductionDepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionDepartmentLayout_ProductionDepartment");
        });

        modelBuilder.Entity<ProductionInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC27C2D0A3EF");

            entity.ToTable("ProductionInfo");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.Color)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FinishQty).HasColumnName("FinishQTY");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.Line)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.Remark).HasMaxLength(255);
            entity.Property(e => e.Spmain)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SPMain");
            entity.Property(e => e.Style)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ProductionDepartment).WithMany(p => p.ProductionInfos)
                .HasForeignKey(d => d.ProductionDepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionInfo_ProductionDepartment");
        });

        modelBuilder.Entity<ProductionMachine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producti__3214EC278D2C1BF7");

            entity.ToTable("ProductionMachine");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())", "DF__ProductionMa__ID__5AEE82B9")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF__Productio__Creat__5CD6CB2B")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.MachineNumber)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.Status).HasDefaultValue(1, "DF__Productio__Statu__5BE2A6F2");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())", "DF__Productio__Updat__5DCAEF64")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ProductionDepartment).WithMany(p => p.ProductionMachines)
                .HasForeignKey(d => d.ProductionDepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductionMachine_ProductionDepartment");
        });

        modelBuilder.Entity<StyleDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StyleDet__3214EC27E2EB92CF");

            entity.ToTable("StyleDetail");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DetailName).HasMaxLength(255);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleInfoId).HasColumnName("StyleInfoID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.StyleInfo).WithMany(p => p.StyleDetails)
                .HasForeignKey(d => d.StyleInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StyleDetail_StyleInfo");
        });

        modelBuilder.Entity<StyleInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StyleInf__3214EC2700146CDE");

            entity.ToTable("StyleInfo");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newsequentialid())")
                .HasColumnName("ID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Keyword).HasMaxLength(255);
            entity.Property(e => e.ProductionDepartmentId).HasColumnName("ProductionDepartmentID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.StyleCode).HasMaxLength(100);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}