// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class StyleInfo
{
    public Guid Id { get; set; }

    public Guid ProductionDepartmentId { get; set; }

    public string StyleCode { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<DailyOutput> DailyOutputs { get; set; } = new List<DailyOutput>();

    public virtual ICollection<StyleDetail> StyleDetails { get; set; } = new List<StyleDetail>();
}