// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class StyleDetail
{
    public Guid Id { get; set; }

    public Guid StyleInfoId { get; set; }

    public string DetailName { get; set; }

    public int Status { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<DailyOutputDetail> DailyOutputDetails { get; set; } = new List<DailyOutputDetail>();

    public virtual StyleInfo StyleInfo { get; set; }
}