// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sub_Entities.Entities;

public partial class User
{
    public Guid Id { get; set; }

    public string Username { get; set; }

    public string Msnv { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string HashCode { get; set; }

    public string FullName { get; set; }

    public string Keyword { get; set; }

    public int Status { get; set; }

    public DateTime ExpiryDate { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? UpdateBy { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<UserPagePermission> UserPagePermissions { get; set; } = new List<UserPagePermission>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}